#!/usr/bin/env bash
#MISE description="Create a private ~/.gitconfig loader for public base and local overlays"
set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.config/dotfiles}"
REPO_GITCONFIG="$DOTFILES_DIR/home/.gitconfig"
REPO_LOCAL_EXAMPLE="$DOTFILES_DIR/home/.gitconfig.local.example"
HOME_GITCONFIG="$HOME/.gitconfig"
HOME_LOCAL="$HOME/.gitconfig.local"
MIGRATION_ROOT="${DOTFILES_MIGRATION_BACKUP_ROOT:-$HOME/.local/share/dotfiles/migration-backups}"

if [[ ! -f "$REPO_GITCONFIG" ]]; then
	echo "FAIL: $REPO_GITCONFIG missing — repo is incomplete" >&2
	exit 1
fi

backup_path() {
	local path="$1" label="$2" backup
	mkdir -p "$MIGRATION_ROOT"
	backup="$MIGRATION_ROOT/${label}-$(date -u +%Y%m%dT%H%M%SZ)-$$"
	mv "$path" "$backup"
	echo "BACKED UP: $path -> $backup"
}

# Extract identity from an existing private file before adding includes. The
# original remains in place; this only seeds the dedicated local overlay.
if [[ -f "$HOME_GITCONFIG" && ! -L "$HOME_GITCONFIG" && ! -e "$HOME_LOCAL" ]] \
	&& grep -q '^\[user\]' "$HOME_GITCONFIG"; then
	{
		echo "# Migrated from ~/.gitconfig on $(date -Iseconds)"
		git config --file "$HOME_GITCONFIG" --get-regexp '^user\.' \
			| awk 'NR==1 {print "[user]"} {sub("^user\\.",""); split($0, p, " "); printf "\t%s = %s\n", p[1], substr($0, length(p[1])+2)}'
	} > "$HOME_LOCAL"
	echo "SEEDED: ~/.gitconfig.local from existing private identity"
fi

# The old topology linked a mutable Git endpoint directly to public source.
# Remove only that legacy link. Any other symlink is ambiguous and is backed up.
if [[ -L "$HOME_GITCONFIG" ]]; then
	current_target="$(readlink "$HOME_GITCONFIG")"
	current_real="$(python3 - "$HOME_GITCONFIG" <<'PY'
import os, sys
print(os.path.realpath(sys.argv[1]))
PY
)"
	repo_real="$(python3 - "$REPO_GITCONFIG" <<'PY'
import os, sys
print(os.path.realpath(sys.argv[1]))
PY
)"
	if [[ "$current_real" == "$repo_real" ]]; then
		rm "$HOME_GITCONFIG"
		echo "MIGRATED: removed legacy ~/.gitconfig -> public source symlink"
	else
		backup_path "$HOME_GITCONFIG" "gitconfig-symlink"
		echo "WARN: preserved unexpected ~/.gitconfig target: $current_target" >&2
	fi
elif [[ -e "$HOME_GITCONFIG" && ! -f "$HOME_GITCONFIG" ]]; then
	backup_path "$HOME_GITCONFIG" "gitconfig-path"
fi

if [[ ! -e "$HOME_GITCONFIG" ]]; then
	{
		echo "# Private Git loader generated by ~/.config/dotfiles."
		echo "# git config --global writes stay in this untracked file."
	} > "$HOME_GITCONFIG"
	echo "CREATED: private ~/.gitconfig loader"
else
	echo "OK: preserving existing private ~/.gitconfig loader"
fi

# Keep exactly one public include followed by exactly one local include. Other
# private includes and settings remain untouched.
git config --file "$HOME_GITCONFIG" --fixed-value --unset-all include.path "$REPO_GITCONFIG" 2>/dev/null || true
git config --file "$HOME_GITCONFIG" --fixed-value --unset-all include.path "$HOME_LOCAL" 2>/dev/null || true
# shellcheck disable=SC2088 # Remove the legacy literal-tilde include spelling.
git config --file "$HOME_GITCONFIG" --fixed-value --unset-all include.path '~/.gitconfig.local' 2>/dev/null || true
git config --file "$HOME_GITCONFIG" --add include.path "$REPO_GITCONFIG"
git config --file "$HOME_GITCONFIG" --add include.path "$HOME_LOCAL"

if [[ -e "$HOME_LOCAL" ]]; then
	echo "OK: ~/.gitconfig.local already exists (left untouched)"
elif [[ -f "$REPO_LOCAL_EXAMPLE" ]]; then
	cp "$REPO_LOCAL_EXAMPLE" "$HOME_LOCAL"
	echo "SEEDED: ~/.gitconfig.local from public example — edit identity locally"
fi

if git config --file "$HOME_GITCONFIG" --list >/dev/null 2>&1; then
	echo "OK: private Git loader parses cleanly"
else
	echo "FAIL: private Git loader failed to parse" >&2
	exit 1
fi

if [[ -z "$(git config --get user.email 2>/dev/null)" ]]; then
	echo "WARN: user.email is empty — edit ~/.gitconfig.local" >&2
fi
